// Date: 11/10/2014 2:44:04 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package helpertools.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class Model_TransformationStaff extends ModelBase
{
  //fields
    ModelRenderer Rod1;
    ModelRenderer Ornbase;
    ModelRenderer OrnLeft;
    ModelRenderer OrnRight;
    ModelRenderer OrnRight2;
    ModelRenderer CapBase;
    ModelRenderer CapLeft;
    ModelRenderer CapRight;
    ModelRenderer Core;
    ModelRenderer Core2;
    ModelRenderer Core3;
    ModelRenderer Core4;
    ModelRenderer Core5;
    ModelRenderer TopperLeft1;
    ModelRenderer TopperLeft2;
    ModelRenderer TopperLeft3;
    ModelRenderer TopperLeft4;
    ModelRenderer TopperRight1;
    ModelRenderer TopperRight2;
    ModelRenderer TopperRight3;
    ModelRenderer TopperRight4;
    ModelRenderer WrapLeft;
    ModelRenderer WrapRight;
  
  public Model_TransformationStaff()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Rod1 = new ModelRenderer(this, 54, 0);
      Rod1.addBox(-1F, 0F, -1F, 2, 20, 2);
      Rod1.setRotationPoint(0F, 0F, 0F);
      Rod1.setTextureSize(64, 32);
      Rod1.mirror = true;
      setRotation(Rod1, 0F, 0F, 0F);
      Ornbase = new ModelRenderer(this, 0, 8);
      Ornbase.addBox(-2F, 0F, -1F, 3, 1, 2);
      Ornbase.setRotationPoint(0.5F, 20F, 0F);
      Ornbase.setTextureSize(64, 32);
      Ornbase.mirror = true;
      setRotation(Ornbase, 0F, 0F, 0F);
      OrnLeft = new ModelRenderer(this, 27, 2);
      OrnLeft.addBox(0F, 0F, -1F, 1, 3, 2);
      OrnLeft.setRotationPoint(-0.5F, 21F, 0F);
      OrnLeft.setTextureSize(64, 32);
      OrnLeft.mirror = true;
      setRotation(OrnLeft, 0F, 0F, 0F);
      OrnRight = new ModelRenderer(this, 13, 10);
      OrnRight.addBox(0F, 0F, -1F, 1, 1, 2);
      OrnRight.setRotationPoint(-1.5F, 22F, 0F);
      OrnRight.setTextureSize(64, 32);
      OrnRight.mirror = true;
      setRotation(OrnRight, 0F, 0F, 0F);
      OrnRight2 = new ModelRenderer(this, 3, 15);
      OrnRight2.addBox(0F, 0F, 0F, 1, 1, 2);
      OrnRight2.setRotationPoint(0.5F, 22F, -1F);
      OrnRight2.setTextureSize(64, 32);
      OrnRight2.mirror = true;
      setRotation(OrnRight2, 0F, 0F, 0F);
      CapBase = new ModelRenderer(this, 27, 27);
      CapBase.addBox(-4F, 0F, -1F, 8, 2, 2);
      CapBase.setRotationPoint(0F, -2F, 0F);
      CapBase.setTextureSize(64, 32);
      CapBase.mirror = true;
      setRotation(CapBase, 0F, 0F, 0F);
      CapLeft = new ModelRenderer(this, 27, 16);
      CapLeft.addBox(0F, 0F, -1F, 1, 2, 2);
      CapLeft.setRotationPoint(2F, 0F, 0F);
      CapLeft.setTextureSize(64, 32);
      CapLeft.mirror = true;
      setRotation(CapLeft, 0F, 0F, 0F);
      CapRight = new ModelRenderer(this, 35, 16);
      CapRight.addBox(0F, 0F, -1F, 1, 2, 2);
      CapRight.setRotationPoint(-3F, 0F, 0F);
      CapRight.setTextureSize(64, 32);
      CapRight.mirror = true;
      setRotation(CapRight, 0F, 0F, 0F);
      Core = new ModelRenderer(this, 0, 26);
      Core.addBox(-1F, 0F, -1F, 2, 1, 2);
      Core.setRotationPoint(0F, -6F, 0F);
      Core.setTextureSize(64, 32);
      Core.mirror = true;
      setRotation(Core, 0F, 0.7853982F, 0F);
      Core2 = new ModelRenderer(this, 0, 24);
      Core2.addBox(-1F, 0F, -1F, 2, 1, 2);
      Core2.setRotationPoint(0F, -4F, 0F);
      Core2.setTextureSize(64, 32);
      Core2.mirror = true;
      setRotation(Core2, 0F, 0.2617994F, 0F);
      Core3 = new ModelRenderer(this, 0, 27);
      Core3.addBox(-1F, 0F, -1F, 2, 1, 2);
      Core3.setRotationPoint(0F, -8F, 0F);
      Core3.setTextureSize(64, 32);
      Core3.mirror = true;
      setRotation(Core3, 0F, 1.308997F, 0F);
      Core4 = new ModelRenderer(this, 0, 27);
      Core4.addBox(-1F, 0F, -1F, 2, 1, 2);
      Core4.setRotationPoint(0F, -7F, 0F);
      Core4.setTextureSize(64, 32);
      Core4.mirror = true;
      setRotation(Core4, 0F, -1.047198F, 0F);
      Core5 = new ModelRenderer(this, 0, 25);
      Core5.addBox(-1F, 0F, -1F, 2, 1, 2);
      Core5.setRotationPoint(0F, -5F, 0F);
      Core5.setTextureSize(64, 32);
      Core5.mirror = true;
      setRotation(Core5, 0F, -0.5235988F, 0F);
      TopperLeft1 = new ModelRenderer(this, 35, 0);
      TopperLeft1.addBox(2F, -3F, -1F, 1, 7, 2);
      TopperLeft1.setRotationPoint(0F, -7F, 0F);
      TopperLeft1.setTextureSize(64, 32);
      TopperLeft1.mirror = true;
      setRotation(TopperLeft1, 0F, 0F, -0.0349066F);
      TopperLeft2 = new ModelRenderer(this, 0, 15);
      TopperLeft2.addBox(3F, 2F, -1F, 1, 1, 2);
      TopperLeft2.setRotationPoint(0F, -7F, 0F);
      TopperLeft2.setTextureSize(64, 32);
      TopperLeft2.mirror = true;
      setRotation(TopperLeft2, 0F, 0F, -0.0349066F);
      TopperLeft3 = new ModelRenderer(this, 0, 15);
      TopperLeft3.addBox(3F, -3F, -1F, 3, 1, 2);
      TopperLeft3.setRotationPoint(0F, -7F, 0F);
      TopperLeft3.setTextureSize(64, 32);
      TopperLeft3.mirror = true;
      setRotation(TopperLeft3, 0F, 0F, -0.0349066F);
      TopperLeft4 = new ModelRenderer(this, 0, 15);
      TopperLeft4.addBox(3F, -1F, -1F, 2, 1, 2);
      TopperLeft4.setRotationPoint(0F, -7F, 0F);
      TopperLeft4.setTextureSize(64, 32);
      TopperLeft4.mirror = true;
      setRotation(TopperLeft4, 0F, 0F, -0.0349066F);
      TopperRight1 = new ModelRenderer(this, 27, 0);
      TopperRight1.addBox(-3F, -3F, -1F, 1, 7, 2);
      TopperRight1.setRotationPoint(0F, -7F, 0F);
      TopperRight1.setTextureSize(64, 32);
      TopperRight1.mirror = true;
      setRotation(TopperRight1, 0F, 0F, 0.0523599F);
      TopperRight2 = new ModelRenderer(this, 0, 20);
      TopperRight2.addBox(-4F, 2F, -1F, 1, 1, 2);
      TopperRight2.setRotationPoint(0F, -7F, 0F);
      TopperRight2.setTextureSize(64, 32);
      TopperRight2.mirror = true;
      setRotation(TopperRight2, 0F, 0F, 0.0523599F);
      TopperRight3 = new ModelRenderer(this, 0, 20);
      TopperRight3.addBox(-6F, -3F, -1F, 3, 1, 2);
      TopperRight3.setRotationPoint(0F, -7F, 0F);
      TopperRight3.setTextureSize(64, 32);
      TopperRight3.mirror = true;
      setRotation(TopperRight3, 0F, 0F, 0.0523599F);
      TopperRight4 = new ModelRenderer(this, 0, 20);
      TopperRight4.addBox(-5F, -1F, -1F, 2, 1, 2);
      TopperRight4.setRotationPoint(0F, -7F, 0F);
      TopperRight4.setTextureSize(64, 32);
      TopperRight4.mirror = true;
      setRotation(TopperRight4, 0F, 0F, 0.0523599F);
      WrapLeft = new ModelRenderer(this, 9, 22);
      WrapLeft.addBox(0F, 0F, -1F, 3, 1, 2);
      WrapLeft.setRotationPoint(1F, 7F, 0F);
      WrapLeft.setTextureSize(64, 32);
      WrapLeft.mirror = true;
      setRotation(WrapLeft, 0.296706F, 0F, 0.5585054F);
      WrapRight = new ModelRenderer(this, 10, 17);
      WrapRight.addBox(-3F, 0F, -1F, 3, 1, 2);
      WrapRight.setRotationPoint(-1F, 7F, 0F);
      WrapRight.setTextureSize(64, 32);
      WrapRight.mirror = true;
      setRotation(WrapRight, -0.296706F, 0F, -0.5585054F);
  }
  
  public void renderModel(float f5){	
    Rod1.render(f5);
    Ornbase.render(f5);
    OrnLeft.render(f5);
    OrnRight.render(f5);
    OrnRight2.render(f5);
    CapBase.render(f5);
    CapLeft.render(f5);
    CapRight.render(f5);
    Core.render(f5);
    Core2.render(f5);
    Core3.render(f5);
    Core4.render(f5);
    Core5.render(f5);
    TopperLeft1.render(f5);
    TopperLeft2.render(f5);
    TopperLeft3.render(f5);
    TopperLeft4.render(f5);
    TopperRight1.render(f5);
    TopperRight2.render(f5);
    TopperRight3.render(f5);
    TopperRight4.render(f5);
    WrapLeft.render(f5);
    WrapRight.render(f5);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
   
  }
    
    
}
