// Date: 11/8/2014 8:42:51 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package helpertools.models;

import helpertools.tools.Staff_Expansion;

import org.lwjgl.opengl.GL11;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class Model_ExpansionStaff extends ModelBase
{
  //fields
    ModelRenderer Rod1;
    ModelRenderer Ornbase;
    ModelRenderer OrnLeft;
    ModelRenderer OrnRight;
    ModelRenderer OrnRight2;
    ModelRenderer CapBase;
    ModelRenderer CapLeft;
    ModelRenderer CapRight;
    ModelRenderer Core;
    ModelRenderer Core2;
    ModelRenderer Core3;
    ModelRenderer Core4;
    ModelRenderer TopperLeft1;
    ModelRenderer TopperLeft2;
    ModelRenderer TopperRight1;
    ModelRenderer TopperRight2;
    ModelRenderer WrapLeft;
    ModelRenderer WrapRight;
    ModelRenderer TopperTop1;
    ModelRenderer TopperTop2;
    ModelRenderer TopperTop3;
  
  public Model_ExpansionStaff()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Rod1 = new ModelRenderer(this, 54, 0);
      Rod1.addBox(-1F, 0F, -1F, 2, 20, 2);
      Rod1.setRotationPoint(0F, 0F, 0F);
      Rod1.setTextureSize(64, 32);
      Rod1.mirror = true;
      setRotation(Rod1, 0F, 0F, 0F);
      Ornbase = new ModelRenderer(this, 0, 8);
      Ornbase.addBox(-2F, 0F, -1F, 3, 1, 2);
      Ornbase.setRotationPoint(0F, 20F, 0F);
      Ornbase.setTextureSize(64, 32);
      Ornbase.mirror = true;
      setRotation(Ornbase, 0F, 0F, 0F);
      OrnLeft = new ModelRenderer(this, 35, 4);
      OrnLeft.addBox(0F, 0F, -1F, 1, 3, 2);
      OrnLeft.setRotationPoint(0F, 21F, 0F);
      OrnLeft.setTextureSize(64, 32);
      OrnLeft.mirror = true;
      setRotation(OrnLeft, 0F, 0F, 0F);
      OrnRight = new ModelRenderer(this, 13, 10);
      OrnRight.addBox(0F, 0F, -1F, 1, 1, 2);
      OrnRight.setRotationPoint(-1F, 23F, 0F);
      OrnRight.setTextureSize(64, 32);
      OrnRight.mirror = true;
      setRotation(OrnRight, 0F, 0F, 0F);
      OrnRight2 = new ModelRenderer(this, 13, 10);
      OrnRight2.addBox(0F, 0F, -1F, 1, 1, 2);
      OrnRight2.setRotationPoint(-2F, 21F, 0F);
      OrnRight2.setTextureSize(64, 32);
      OrnRight2.mirror = true;
      setRotation(OrnRight2, 0F, 0F, 0F);
      CapBase = new ModelRenderer(this, 27, 27);
      CapBase.addBox(-4F, 0F, -1F, 8, 2, 2);
      CapBase.setRotationPoint(0F, -2F, 0F);
      CapBase.setTextureSize(64, 32);
      CapBase.mirror = true;
      setRotation(CapBase, 0F, 0F, 0F);
      CapLeft = new ModelRenderer(this, 27, 16);
      CapLeft.addBox(0F, 0F, -1F, 1, 2, 2);
      CapLeft.setRotationPoint(3F, 0F, 0F);
      CapLeft.setTextureSize(64, 32);
      CapLeft.mirror = true;
      setRotation(CapLeft, 0F, 0F, 0F);
      CapRight = new ModelRenderer(this, 35, 16);
      CapRight.addBox(0F, 0F, -1F, 1, 2, 2);
      CapRight.setRotationPoint(-4F, 0F, 0F);
      CapRight.setTextureSize(64, 32);
      CapRight.mirror = true;
      setRotation(CapRight, 0F, 0F, 0F);
      Core = new ModelRenderer(this, 0, 26);
      Core.addBox(1F, -1F, -1F, 1, 2, 2);
      Core.setRotationPoint(-0F, -0F, 0F);
      Core.setTextureSize(64, 32);
      Core.mirror = true;
      setRotation(Core, -0.1487144F, 0F, 0F);
      Core2 = new ModelRenderer(this, 0, 25);
      Core2.addBox(2F, -1F, -1F, 1, 2, 2);
      //Core3.setRotationPoint(-2F, -5F, 0F);
      Core2.setRotationPoint(-0F, -0F, 0F);
      Core2.setTextureSize(64, 32);
      Core2.mirror = true;
      setRotation(Core2, -0.3866576F, 0F, 0F);
      Core3 = new ModelRenderer(this, 0, 24);
      Core3.addBox(3F, -1F, -1F, 1, 2, 2);
      Core3.setRotationPoint(-0F, -0F, 0F);
      Core3.setTextureSize(64, 32);
      Core3.mirror = true;
      setRotation(Core3, -0.7733151F, 0F, 0F);
      Core4 = new ModelRenderer(this, 1, 26);
      Core4.addBox(0F, -1F, -1F, 1, 2, 2);
      Core4.setRotationPoint(-0F, -0F, 0F);
      Core4.setTextureSize(64, 32);
      Core4.mirror = true;
      setRotation(Core4, 0.1189716F, 0F, 0F);
      TopperLeft1 = new ModelRenderer(this, 35, 0);
      TopperLeft1.addBox(0F, 0F, -1F, 1, 7, 2);
      TopperLeft1.setRotationPoint(3F, -10F, 0F);
      TopperLeft1.setTextureSize(64, 32);
      TopperLeft1.mirror = true;
      setRotation(TopperLeft1, 0F, 0F, 0F);
      TopperLeft2 = new ModelRenderer(this, 0, 15);
      TopperLeft2.addBox(0F, 0F, -1F, 1, 1, 2);
      TopperLeft2.setRotationPoint(4F, -5F, 0F);
      TopperLeft2.setTextureSize(64, 32);
      TopperLeft2.mirror = true;
      setRotation(TopperLeft2, 0F, 0F, 0F);
      TopperRight1 = new ModelRenderer(this, 27, 0);
      TopperRight1.addBox(0F, 0F, -1F, 1, 7, 2);
      TopperRight1.setRotationPoint(-4F, -10F, 0F);
      TopperRight1.setTextureSize(64, 32);
      TopperRight1.mirror = true;
      setRotation(TopperRight1, 0F, 0F, 0F);
      TopperRight2 = new ModelRenderer(this, 0, 20);
      TopperRight2.addBox(0F, 0F, -1F, 1, 1, 2);
      TopperRight2.setRotationPoint(-5F, -5F, 0F);
      TopperRight2.setTextureSize(64, 32);
      TopperRight2.mirror = true;
      setRotation(TopperRight2, 0F, 0F, 0F);
      WrapLeft = new ModelRenderer(this, 9, 22);
      WrapLeft.addBox(0F, 0F, -1F, 3, 1, 2);
      WrapLeft.setRotationPoint(1F, 7F, 0F);
      WrapLeft.setTextureSize(64, 32);
      WrapLeft.mirror = true;
      setRotation(WrapLeft, 0.296706F, 0F, 0.5585054F);
      WrapRight = new ModelRenderer(this, 10, 17);
      WrapRight.addBox(-3F, 0F, -1F, 3, 1, 2);
      WrapRight.setRotationPoint(-1F, 7F, 0F);
      WrapRight.setTextureSize(64, 32);
      WrapRight.mirror = true;
      setRotation(WrapRight, -0.296706F, 0F, -0.5585054F);
      TopperTop1 = new ModelRenderer(this, 35, 0);
      TopperTop1.addBox(0F, -3F, -1F, 1, 6, 2);
      TopperTop1.setRotationPoint(0F, -8.5F, 0F);
      TopperTop1.setTextureSize(64, 32);
      TopperTop1.mirror = true;
      setRotation(TopperTop1, 0F, 0F, 1.570796F);
      TopperTop2 = new ModelRenderer(this, 35, 3);
      TopperTop2.addBox(0F, 0F, -1F, 1, 3, 2);
      TopperTop2.setRotationPoint(1F, -11.5F, 0F);
      TopperTop2.setTextureSize(64, 32);
      TopperTop2.mirror = true;
      setRotation(TopperTop2, 0F, 0F, 0F);
      TopperTop3 = new ModelRenderer(this, 35, 3);
      TopperTop3.addBox(0F, 0F, -1F, 1, 3, 2);
      TopperTop3.setRotationPoint(-2F, -11.5F, 0F);
      TopperTop3.setTextureSize(64, 32);
      TopperTop3.mirror = true;
      setRotation(TopperTop3, 0F, 0F, 0F);
  }
  
  public void renderModel(ItemStack item, float f5){
	 
	  Staff_Expansion  entitywolf = (Staff_Expansion)item.getItem();
	  	  
	  ///////////////////////////////
	  
		  GL11.glPushMatrix();
		  //GL11.glTranslatef(0.0F, -8.0F * f5, 0.0F);
		  //Rod1.render(f5);
		  //
		  GL11.glTranslatef(-1.25F,-3F,0F);
		  //GL11.glRotatef(entitywolf.getSpinDec(item), 1F,0F,0F);
		  Core.render(f5);
		    Core2.render(f5);
		    Core3.render(f5);
		    Core4.render(f5);
		  //
		  GL11.glPopMatrix();
	  
	  //////////////////////////////
	  
	Rod1.render(f5);
    Ornbase.render(f5);
    OrnLeft.render(f5);
    OrnRight.render(f5);
    OrnRight2.render(f5);
    CapBase.render(f5);
    CapLeft.render(f5);
    CapRight.render(f5);
    
    //Core.render(f5);
    //Core2.render(f5);
    //Core3.render(f5);
    //Core4.render(f5);
    
     
    WrapLeft.render(f5);
    WrapRight.render(f5);    
    TopperLeft1.render(f5);
    TopperLeft2.render(f5);
    TopperRight1.render(f5);
    TopperRight2.render(f5);    
    TopperTop1.render(f5);
    TopperTop2.render(f5);
    TopperTop3.render(f5);
    
   
	  
    
  }
  

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
   
   
    
    
    
    
  }
}
