// Date: 1/21/2015 3:45:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package helpertools.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;

public class Model_EuclideanStaff extends ModelBase
{
  //fields
    ModelRenderer Rod1;
    ModelRenderer CapBase;
    ModelRenderer CapBase2;
    ModelRenderer TopperLeft1;
    ModelRenderer TopperLeft2;
    ModelRenderer TopperLeft3;
    ModelRenderer TopperLeft4;
    ModelRenderer TopperRight1;
    ModelRenderer TopperRight2;
    ModelRenderer TopperRight3;
    ModelRenderer TopperRight5;
    ModelRenderer TopperRight6;
    ModelRenderer WrapLeft;
    ModelRenderer WrapRight;
    ModelRenderer Core1;
    ModelRenderer Core2;
    ModelRenderer Core3;
    ModelRenderer Core4;
    ModelRenderer TopperLeft5;
    ModelRenderer CapBase3;
    ModelRenderer CapBase4;
    ModelRenderer OrnBase;
    ModelRenderer OrnBase2;
    ModelRenderer OrnBase3;
    ModelRenderer OrnBase4;
  
  public Model_EuclideanStaff()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Rod1 = new ModelRenderer(this, 55, 1);
      Rod1.addBox(-1F, 0F, -1F, 2, 20, 2);
      Rod1.setRotationPoint(0F, -1F, 0F);
      Rod1.setTextureSize(64, 32);
      Rod1.mirror = true;
      setRotation(Rod1, 0F, 0F, 0F);
      
      CapBase = new ModelRenderer(this, 29, 16);
      CapBase.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
      CapBase.setRotationPoint(0F, -4F, 0F);
      CapBase.setTextureSize(64, 32);
      CapBase.mirror = true;
      setRotation(CapBase, 0F, 0.7853982F, 0F);
      
      CapBase2 = new ModelRenderer(this, 29, 16);
      CapBase2.addBox(-1.5F, -10F, -1.5F, 3, 3, 3);
      CapBase2.setRotationPoint(0F, -4F, 0F);
      CapBase2.setTextureSize(64, 32);
      CapBase2.mirror = true;
      setRotation(CapBase2, 0F, 0.7853982F, 0F);
      
      TopperLeft1 = new ModelRenderer(this, 36, 23);
      TopperLeft1.addBox(3.5F, -3F, -1F, 1, 7, 2);
      TopperLeft1.setRotationPoint(1F, -8F, 0F);
      TopperLeft1.setTextureSize(64, 32);
      TopperLeft1.mirror = true;
      setRotation(TopperLeft1, 0F, 0F, 0.0174533F);
      
      TopperLeft2 = new ModelRenderer(this, 36, 23);
      TopperLeft2.addBox(4.5F, -3F, -1F, 7, 1, 2);
      TopperLeft2.setRotationPoint(1F, -8F, 0F);
      TopperLeft2.setTextureSize(64, 32);
      TopperLeft2.mirror = true;
      setRotation(TopperLeft2, 0F, 0F, 0.0174533F);
      
      TopperLeft3 = new ModelRenderer(this, 36, 23);
      TopperLeft3.addBox(4.5F, 2F, -1F, 3, 1, 2);
      TopperLeft3.setRotationPoint(1F, -7F, 0F);
      TopperLeft3.setTextureSize(64, 32);
      TopperLeft3.mirror = true;
      setRotation(TopperLeft3, 0F, 0F, 0.0174533F);
      
      TopperLeft4 = new ModelRenderer(this, 36, 23);
      TopperLeft4.addBox(7.5F, -1F, -1F, 1, 4, 2);
      TopperLeft4.setRotationPoint(1F, -7F, 0F);
      TopperLeft4.setTextureSize(64, 32);
      TopperLeft4.mirror = true;
      setRotation(TopperLeft4, 0F, 0F, 0.0174533F);
      
      TopperRight1 = new ModelRenderer(this, 31, 23);
      TopperRight1.addBox(-4.5F, -4F, -1F, 1, 7, 2);
      TopperRight1.setRotationPoint(-1F, -7F, 0F);
      TopperRight1.setTextureSize(64, 32);
      TopperRight1.mirror = true;
      setRotation(TopperRight1, 0F, 0F, -0.0174533F);
      
      TopperRight2 = new ModelRenderer(this, 31, 23);
      TopperRight2.addBox(-11.5F, -4F, -1F, 7, 1, 2);
      TopperRight2.setRotationPoint(-1F, -7F, 0F);
      TopperRight2.setTextureSize(64, 32);
      TopperRight2.mirror = true;
      setRotation(TopperRight2, 0F, 0F, -0.0174533F);
      
      TopperRight3 = new ModelRenderer(this, 31, 27);
      TopperRight3.addBox(-7.5F, 2F, -1F, 3, 1, 2);
      TopperRight3.setRotationPoint(-1F, -7F, 0F);
      TopperRight3.setTextureSize(64, 32);
      TopperRight3.mirror = true;
      setRotation(TopperRight3, 0F, 0F, -0.0174533F);
      
      TopperRight5 = new ModelRenderer(this, 31, 26);
      TopperRight5.addBox(-8.5F, -1F, -1F, 1, 4, 2);
      TopperRight5.setRotationPoint(-1F, -7F, 0F);
      TopperRight5.setTextureSize(64, 32);
      TopperRight5.mirror = true;
      setRotation(TopperRight5, 0F, 0F, -0.0174533F);
      
      TopperRight6 = new ModelRenderer(this, 42, 27);
      TopperRight6.addBox(-7.5F, -1F, -1F, 2, 1, 2);
      TopperRight6.setRotationPoint(-1F, -7F, 0F);
      TopperRight6.setTextureSize(64, 32);
      TopperRight6.mirror = true;
      setRotation(TopperRight6, 0F, 0F, -0.0174533F);
      
      WrapLeft = new ModelRenderer(this, 54, 29);
      WrapLeft.addBox(0F, 0F, -1F, 3, 1, 2);
      WrapLeft.setRotationPoint(1F, 5F, 0F);
      WrapLeft.setTextureSize(64, 32);
      WrapLeft.mirror = true;
      setRotation(WrapLeft, 0.296706F, 0F, 0.5585054F);
      
    
      WrapRight = new ModelRenderer(this, 54, 24);
      WrapRight.addBox(-3F, 0F, -1F, 3, 1, 2);
      WrapRight.setRotationPoint(-1F, 7F, 0F);
      WrapRight.setTextureSize(64, 32);
      WrapRight.mirror = true;
      setRotation(WrapRight, -0.296706F, 0F, -0.5585054F);
      
      
      Core1 = new ModelRenderer(this, 3, 23);
      Core1.addBox(0.5F, 0F, -0.5F, 1, 7, 1);
      Core1.setRotationPoint(0F, -11F, 0F);
      Core1.setTextureSize(64, 32);
      Core1.mirror = true;
      setRotation(Core1, 0F, 0F, 0F);
      
      Core2 = new ModelRenderer(this, 1, 23);
      Core2.addBox(-1.5F, 0F, -0.5F, 1, 7, 1);
      Core2.setRotationPoint(0F, -11F, 0F);
      Core2.setTextureSize(64, 32);
      Core2.mirror = true;
      setRotation(Core2, 0F, 0F, 0F);
      
      Core3 = new ModelRenderer(this, 4, 24);
      Core3.addBox(-0.5F, 0F, 0.5F, 1, 7, 1);
      Core3.setRotationPoint(0F, -11F, 0F);
      Core3.setTextureSize(64, 32);
      Core3.mirror = true;
      setRotation(Core3, 0F, 0F, 0F);
      
      Core4 = new ModelRenderer(this, 6, 24);
      Core4.addBox(-0.5F, 0F, -1.5F, 1, 7, 1);
      Core4.setRotationPoint(0F, -11F, 0F);
      Core4.setTextureSize(64, 32);
      Core4.mirror = true;
      setRotation(Core4, 0F, 0F, 0F);
      
      TopperLeft5 = new ModelRenderer(this, 36, 23);
      TopperLeft5.addBox(5.5F, -1F, -1F, 2, 1, 2);
      TopperLeft5.setRotationPoint(1F, -7F, 0F);
      TopperLeft5.setTextureSize(64, 32);
      TopperLeft5.mirror = true;
      setRotation(TopperLeft5, 0F, 0F, 0.0174533F);
      
      CapBase3 = new ModelRenderer(this, 0, 5);
      CapBase3.addBox(-2F, 0F, -2F, 4, 1, 4);
      CapBase3.setRotationPoint(0F, -3F, 0F);
      CapBase3.setTextureSize(64, 32);
      CapBase3.mirror = true;
      setRotation(CapBase3, 0F, 0.7853982F, 0F);
      
      CapBase4 = new ModelRenderer(this, 0, 11);
      CapBase4.addBox(-2F, -1F, -2F, 4, 1, 4);
      CapBase4.setRotationPoint(0F, -12F, 0F);
      CapBase4.setTextureSize(64, 32);
      CapBase4.mirror = true;
      setRotation(CapBase4, 0F, 0.7853982F, 0F);
      
      OrnBase = new ModelRenderer(this, 29, 16);
      OrnBase.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
      OrnBase.setRotationPoint(0F, 19F, 0F);
      OrnBase.setTextureSize(64, 32);
      OrnBase.mirror = true;
      setRotation(OrnBase, 0F, 0.7853982F, 0F);
      
      OrnBase2 = new ModelRenderer(this, 0, 0);
      OrnBase2.addBox(-2F, 0F, -2F, 4, 1, 4);
      OrnBase2.setRotationPoint(0F, 20F, 0F);
      OrnBase2.setTextureSize(64, 32);
      OrnBase2.mirror = true;
      setRotation(OrnBase2, 0F, 0.7853982F, 0F);
      
      OrnBase3 = new ModelRenderer(this, 2, 18);
      OrnBase3.addBox(0F, 0F, 0F, 1, 1, 1);
      OrnBase3.setRotationPoint(-0.5F, 21.5F, 0F);
      OrnBase3.setTextureSize(64, 32);
      OrnBase3.mirror = true;
      setRotation(OrnBase3, 0F, 0.7853982F, 0F);
      
      OrnBase4 = new ModelRenderer(this, 2, 18);
      OrnBase4.addBox(0.5F, -3F, 0.5F, 1, 1, 1);
      OrnBase4.setRotationPoint(-1.5F, -11.5F, 0F);
      OrnBase4.setTextureSize(64, 32);
      OrnBase4.mirror = true;
      setRotation(OrnBase4, 0F, 0.7853982F, 0F);
  }
  
  public void renderModel(ItemStack item,float f5)
  {
    Rod1.render(f5);
    CapBase.render(f5);
    CapBase2.render(f5);
    TopperLeft1.render(f5);
    TopperLeft2.render(f5);
    TopperLeft3.render(f5);
    TopperLeft4.render(f5);
    TopperRight1.render(f5);
    TopperRight2.render(f5);
    TopperRight3.render(f5);
    TopperRight5.render(f5);
    TopperRight6.render(f5);
    WrapLeft.render(f5);
    WrapRight.render(f5);
    Core1.render(f5);
    Core2.render(f5);
    Core3.render(f5);
    Core4.render(f5);
    TopperLeft5.render(f5);
    CapBase3.render(f5);
    CapBase4.render(f5);
    OrnBase.render(f5);
    OrnBase2.render(f5);
    OrnBase3.render(f5);
    OrnBase4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
   
  }
    
    
}