// Date: 11/19/2014 3:28:20 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package helpertools.models;

import org.lwjgl.opengl.GL11;

import helpertools.tools.ItemStaffofExpansion;
import helpertools.tools.ItemTorchLauncher;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.item.ItemStack;

public class ModelTorchLauncher1 extends ModelBase
{
  //fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer Lip1;
    ModelRenderer Lip2;
    ModelRenderer Lip3;
    ModelRenderer ArmR1;
    ModelRenderer ArmR2;
    ModelRenderer ArmL1;
    ModelRenderer ArmL2;
    ModelRenderer Box1;
    ModelRenderer Box2;
    ModelRenderer Box3;
    ModelRenderer String1;
    ModelRenderer Grip;
    ModelRenderer Griphole1;
    ModelRenderer Gripslot1;
    ModelRenderer Torch1;
    ModelRenderer Torch2;
    ModelRenderer TorchD3;
    ModelRenderer Arm2L1;
    ModelRenderer Arm2L2;
    ModelRenderer Arm2R1;
    ModelRenderer Arm2R2;
    ModelRenderer String2R1;
    ModelRenderer String2L1;
    //
    ModelRenderer Bolt1;
    ModelRenderer Bolt2;
    ModelRenderer Box4;
  
  public ModelTorchLauncher1()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Base1 = new ModelRenderer(this, 1, 52);
      Base1.addBox(-1.5F, 0F, -5F, 3, 1, 11);
      Base1.setRotationPoint(0F, 0F, 0F);
      Base1.setTextureSize(64, 64);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 1, 30);
      Base2.addBox(0.8F, 0F, -5F, 1, 1, 9);
      Base2.setRotationPoint(0F, -1F, 0F);
      Base2.setTextureSize(64, 64);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Base3 = new ModelRenderer(this, 1, 41);
      Base3.addBox(-1.8F, -1F, -5F, 1, 1, 9);
      Base3.setRotationPoint(0F, 0F, 0F);
      Base3.setTextureSize(64, 64);
      Base3.mirror = true;
      setRotation(Base3, 0F, 0F, 0F);
      Lip1 = new ModelRenderer(this, 13, 16);
      Lip1.addBox(-1F, -0.5F, 0F, 2, 3, 1);
      Lip1.setRotationPoint(0F, 0.5F, -6F);
      Lip1.setTextureSize(64, 64);
      Lip1.mirror = true;
      setRotation(Lip1, 0.3490659F, 0F, 0F);
      Lip2 = new ModelRenderer(this, 6, 16);
      Lip2.addBox(1F, -2.2F, -2F, 1, 3, 1);
      Lip2.setRotationPoint(0F, 0F, -4F);
      Lip2.setTextureSize(64, 64);
      Lip2.mirror = true;
      setRotation(Lip2, 0F, 0F, 0F);
      Lip3 = new ModelRenderer(this, 1, 16);
      Lip3.addBox(-2F, -2.2F, -2F, 1, 3, 1);
      Lip3.setRotationPoint(0F, 0F, -4F);
      Lip3.setTextureSize(64, 64);
      Lip3.mirror = true;
      setRotation(Lip3, 0F, 0F, 0F);
      ArmR1 = new ModelRenderer(this, 1, 12);
      ArmR1.addBox(2F, -1F, -1F, 4, 1, 1);
      ArmR1.setRotationPoint(0F, -1F, -6F);
      ArmR1.setTextureSize(64, 64);
      ArmR1.mirror = true;
      setRotation(ArmR1, 0F, -0.5235988F, 0F);
      ArmR2 = new ModelRenderer(this, 13, 8);
      ArmR2.addBox(5.8F, -1F, -2.05F, 2, 1, 1);
      ArmR2.setRotationPoint(0F, -1F, -6F);
      ArmR2.setTextureSize(64, 64);
      ArmR2.mirror = true;
      setRotation(ArmR2, 0F, -0.7020561F, 0F);
      ArmL1 = new ModelRenderer(this, 1, 8);
      ArmL1.addBox(2F, -1F, 0F, 4, 1, 1);
      ArmL1.setRotationPoint(0F, -1F, -6F);
      ArmL1.setTextureSize(64, 64);
      ArmL1.mirror = true;
      setRotation(ArmL1, 0F, -2.617994F, 0F);
      ArmL2 = new ModelRenderer(this, 13, 12);
      ArmL2.addBox(5.8F, -1F, 1F, 2, 1, 1);
      ArmL2.setRotationPoint(0F, -1F, -6F);
      ArmL2.setTextureSize(64, 64);
      ArmL2.mirror = true;
      setRotation(ArmL2, 0F, -2.443461F, 0F);
      Box1 = new ModelRenderer(this, 36, 1);
      Box1.addBox(-1F, 0F, 0F, 2, 2, 3);
      Box1.setRotationPoint(0F, 1F, -4.2F);
      Box1.setTextureSize(64, 64);
      Box1.mirror = true;
      setRotation(Box1, 0F, 0F, 0F);
      Box2 = new ModelRenderer(this, 13, 1);
      Box2.addBox(-1F, 0F, 0F, 2, 2, 3);
      Box2.setRotationPoint(0F, 1F, -4.2F);
      Box2.setTextureSize(64, 64);
      Box2.mirror = true;
      setRotation(Box2, 0F, 0F, 0F);
      Box3 = new ModelRenderer(this, 24, 1);
      Box3.addBox(0F, 0F, 0F, 2, 2, 3);
      Box3.setRotationPoint(-1F, 1F, -4.2F);
      Box3.setTextureSize(64, 64);
      Box3.mirror = true;
      setRotation(Box3, 0F, 0F, 0F);
      String1 = new ModelRenderer(this, 1, 25);
      String1.addBox(-6.5F, 0F, 0F, 13, 1, 1);
      String1.setRotationPoint(0F, -2F, -3F);
      String1.setTextureSize(64, 64);
      String1.mirror = true;
      setRotation(String1, 0F, 0F, 0F);
      Grip = new ModelRenderer(this, 22, 8);
      Grip.addBox(0F, 0F, 0F, 1, 2, 1);
      Grip.setRotationPoint(-0.5F, 1F, 2F);
      Grip.setTextureSize(64, 64);
      Grip.mirror = true;
      setRotation(Grip, 0F, 0F, 0F);
      Griphole1 = new ModelRenderer(this, 22, 8);
      Griphole1.addBox(0.5F, 1F, 0.6F, 1, 1, 1);
      Griphole1.setRotationPoint(-1F, 0F, 0F);
      Griphole1.setTextureSize(64, 64);
      Griphole1.mirror = true;
      setRotation(Griphole1, 0F, 0F, 0F);
      Gripslot1 = new ModelRenderer(this, 22, 8);
      Gripslot1.addBox(-1F, 0.5F, 0F, 1, 1, 1);
      Gripslot1.setRotationPoint(0.5F, 0F, -1F);
      Gripslot1.setTextureSize(64, 64);
      Gripslot1.mirror = true;
      setRotation(Gripslot1, -0.7853982F, 0F, 0F);
      Torch1 = new ModelRenderer(this, 44, 36);
      Torch1.addBox(0F, 0F, 0F, 1, 1, 6);
      Torch1.setRotationPoint(0F, -2F, -5F);
      Torch1.setTextureSize(64, 64);
      Torch1.mirror = true;
      setRotation(Torch1, 0F, 0F, 0.7853982F);
      Torch2 = new ModelRenderer(this, 44, 45);
      Torch2.addBox(0F, 0F, 0F, 1, 1, 6);
      Torch2.setRotationPoint(0F, -2F, -5F);
      Torch2.setTextureSize(64, 64);
      Torch2.mirror = true;
      setRotation(Torch2, 0F, 0F, 0.7853982F);
      TorchD3 = new ModelRenderer(this, 44, 55);
      TorchD3.addBox(0F, 0F, 0F, 1, 1, 6);
      TorchD3.setRotationPoint(0F, -2F, -5F);
      TorchD3.setTextureSize(64, 64);
      TorchD3.mirror = true;
      setRotation(TorchD3, 0F, 0F, 0.7853982F);
      Arm2L1 = new ModelRenderer(this, 1, 8);
      Arm2L1.addBox(1.8F, -1F, 0.3F, 4, 1, 1);
      Arm2L1.setRotationPoint(0F, -1F, -6F);
      Arm2L1.setTextureSize(64, 64);
      Arm2L1.mirror = true;
      setRotation(Arm2L1, 0F, -2.268928F, 0F);
      Arm2L2 = new ModelRenderer(this, 13, 12);
      Arm2L2.addBox(5F, -1F, 2.2F, 2, 1, 1);
      Arm2L2.setRotationPoint(0F, -1F, -6F);
      Arm2L2.setTextureSize(64, 64);
      Arm2L2.mirror = true;
      setRotation(Arm2L2, 0F, -1.919862F, 0F);
      Arm2R1 = new ModelRenderer(this, 1, 8);
      Arm2R1.addBox(1.8F, -1F, -1.3F, 4, 1, 1);
      Arm2R1.setRotationPoint(0F, -1F, -6F);
      Arm2R1.setTextureSize(64, 64);
      Arm2R1.mirror = true;
      setRotation(Arm2R1, 0F, -0.8726646F, 0F);
      Arm2R2 = new ModelRenderer(this, 13, 12);
      Arm2R2.addBox(5F, -1F, -3.2F, 2, 1, 1);
      Arm2R2.setRotationPoint(0F, -1F, -6F);
      Arm2R2.setTextureSize(64, 64);
      Arm2R2.mirror = true;
      setRotation(Arm2R2, 0F, -1.22173F, 0F);
      String2R1 = new ModelRenderer(this, 9, 25);
      String2R1.addBox(-0.4F, 0F, 0F, 5, 1, 1);
      String2R1.setRotationPoint(0F, -2F, 0.2F);
      String2R1.setTextureSize(64, 64);
      String2R1.mirror = true;
      setRotation(String2R1, 0F, 0.3490659F, 0F);
      String2L1 = new ModelRenderer(this, 26, 32);
      String2L1.addBox(-4.6F, 0F, 0.2F, 5, 1, 1);
      String2L1.setRotationPoint(0F, -2F, 0F);
      String2L1.setTextureSize(64, 64);
      String2L1.mirror = true;
      setRotation(String2L1, 0F, -0.3490659F, 0F);
      //
      Box4 = new ModelRenderer(this, 28, 9);
      Box4.addBox(-1F, 0F, -4.2F, 2, 2, 3);
      Box4.setRotationPoint(0F, 1F, 0F);
      Box4.setTextureSize(64, 64);
      Box4.mirror = true;
      setRotation(Box4, 0F, 0F, 0F);
      Bolt1 = new ModelRenderer(this, 31, 7);
      Bolt1.addBox(-0.8F, -2.25F, 0F, 1, 5, 16);
      Bolt1.setRotationPoint(0F, -4.5F, -8F);
      Bolt1.setTextureSize(64, 64);
      Bolt1.mirror = true;
      setRotation(Bolt1, 0F, 0F, -0.7853982F);
      Bolt2 = new ModelRenderer(this, 31, 7);
      Bolt2.addBox(-1F, -3F, 0F, 1, 5, 16);
      Bolt2.setRotationPoint(0F, -4F, -8F);
      Bolt2.setTextureSize(64, 64);
      Bolt2.mirror = true;
      setRotation(Bolt2, 0F, 0F, 0.7853982F);
  }
  
  public void renderModel(ItemStack item, float f5){
		 
	  ItemTorchLauncher ThisStack = (ItemTorchLauncher )item.getItem();
	  
	  //Boxes
	  
	  if (ThisStack.getMode(item) == 2
			  ||ThisStack.getMode(item) == 1){
		  GL11.glPushMatrix();
		  //Vanilla Torch
		  //Torch1.render(f5);
		  Box2.render(f5);
		  
		  GL11.glPopMatrix();
		  
	  }
	  if (ThisStack.getMode(item) == 6
			  ||ThisStack.getMode(item) == 5){
		  //Dynamite
		  GL11.glPushMatrix();
		  //TorchD3.render(f5);
		  Box1.render(f5);
		  
		  GL11.glPopMatrix();
	  }
	  if (ThisStack.getMode(item) == 4
			  ||ThisStack.getMode(item) == 3){
		  //Redstone Torch
		  GL11.glPushMatrix();
		  //Torch2.render(f5);
		  Box3.render(f5);
		  
		  GL11.glPopMatrix();
	  }
	  if (ThisStack.getMode(item) == 8
			  ||ThisStack.getMode(item) == 7){
		  //Arrows
		  GL11.glPushMatrix();
		  Box4.render(f5);
		  
		  GL11.glPopMatrix();
	  }
	  //Loaded Ammo
	  if (ThisStack.getMode(item) == 2 &&ThisStack.getTload(item) == 2
			  ||ThisStack.getMode(item) == 1 &&ThisStack.getTload(item) == 2){
		  GL11.glPushMatrix();
		  //Vanilla Torch
		  Torch1.render(f5);
		  
		  GL11.glPopMatrix();
		  
	  }
	  if (ThisStack.getMode(item) == 6 &&ThisStack.getTload(item) == 2
			  ||ThisStack.getMode(item) == 5 &&ThisStack.getTload(item) == 2){
		  //Dynamite
		  GL11.glPushMatrix();
		  TorchD3.render(f5);
		  
		  GL11.glPopMatrix();
	  }
	  if (ThisStack.getMode(item) == 4 &&ThisStack.getTload(item) == 2
			  ||ThisStack.getMode(item) == 3 &&ThisStack.getTload(item) == 2){
		  //Redstone Torch
		  GL11.glPushMatrix();
		  Torch2.render(f5);
		  
		  GL11.glPopMatrix();
	  }
	  if (ThisStack.getMode(item) == 8 &&ThisStack.getTload(item) == 2
			  ||ThisStack.getMode(item) == 7 &&ThisStack.getTload(item) == 2){
		  //Arrow Bolt
		  GL11.glPushMatrix();
		  GL11.glScalef(.4F,.4F,.4F);
		  GL11.glTranslatef(-.1F,.3F,-3.2F);
		  GL11.glRotatef(3, 0F,0F,-1F);
		  Bolt1.render(f5);
		  Bolt2.render(f5);
		  
		  GL11.glPopMatrix();
	  }
		  
		  //Crossbow Arms
	  if (ThisStack.getTload(item) == 2){
		  GL11.glPushMatrix();
		  	Arm2L1.render(f5);
		    Arm2L2.render(f5);
		    Arm2R1.render(f5);
		    Arm2R2.render(f5);
		    String2R1.render(f5);
		    String2L1.render(f5);
		    
			GL11.glPopMatrix();
		  }
	  if (ThisStack.getTload(item) == 0){
		  GL11.glPushMatrix();
		  	ArmR1.render(f5);
		    ArmR2.render(f5);
		    ArmL1.render(f5);
		    ArmL2.render(f5);
		    String1.render(f5);
		    
			GL11.glPopMatrix();
	  }
	   
		   
		   
		  
	
    Base1.render(f5);
    Base2.render(f5);
    Base3.render(f5);
    Lip1.render(f5);
    Lip2.render(f5);
    Lip3.render(f5);
    //ArmR1.render(f5);
    //ArmR2.render(f5);
    //ArmL1.render(f5);
    //ArmL2.render(f5);
    //Box1.render(f5);
    //Box2.render(f5);
    //Box3.render(f5);
    //String1.render(f5);
    Grip.render(f5);
    Griphole1.render(f5);
    Gripslot1.render(f5);
    //Torch1.render(f5);
    //Torch2.render(f5);
    //TorchD3.render(f5);
    //Arm2L1.render(f5);
    //Arm2L2.render(f5);
    //Arm2R1.render(f5);
    //Arm2R2.render(f5);
    //String2R1.render(f5);
    //String2L1.render(f5);
  }
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    
   
  }
    
    
}
